# Generated by Django 4.2.1 on 2023-06-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stid', models.IntegerField()),
                ('stname', models.CharField(max_length=50)),
                ('stclass', models.CharField(max_length=10)),
                ('stemal', models.EmailField(max_length=40)),
                ('stpas', models.CharField(max_length=20)),
            ],
        ),
    ]
