# Generated by Django 4.2.1 on 2023-06-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='staddress',
            field=models.TextField(default='Demo Address', max_length=200),
        ),
    ]
