# Generated by Django 4.2.1 on 2023-06-12 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_student_staddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='stemal',
            new_name='stemail',
        ),
    ]
