# Generated by Django 4.2.2 on 2023-10-03 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_fields_app', '0002_alter_user_agree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='agree',
            field=models.BooleanField(),
        ),
    ]
