# Generated by Django 4.2.1 on 2023-07-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createview_app', '0002_teacher_alter_students_middle_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'SchoolStaff',
                'verbose_name_plural': 'SchoolStaffs',
            },
        ),
    ]
