# Generated by Django 4.2.1 on 2023-07-12 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'SchoolStaff',
                'verbose_name_plural': 'SchoolStaffs',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('middle_name', models.CharField(blank=True, max_length=15, null=True)),
                ('last_name', models.CharField(max_length=15)),
                ('roll', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('class_name', models.CharField(max_length=15)),
                ('section', models.CharField(max_length=2)),
            ],
        ),
    ]
