# Generated by Django 4.2.1 on 2023-07-29 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('class_name', models.CharField(max_length=10)),
                ('roll', models.IntegerField(unique=True)),
                ('pass_date', models.DateField()),
                ('city', models.CharField(max_length=30)),
            ],
        ),
    ]
